"""empty message

Revision ID: 632b29a28764
Revises: 
Create Date: 2019-12-16 16:20:08.351077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632b29a28764'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
